apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pdvd-helmrelease.yaml
  - values.yaml

secretGenerator:
  - name: pdvd-secrets
    files:
      - secrets.enc.yaml
generatorOptions:
  disableNameSuffixHash: true
