apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pdvd-helmrelease.yaml  # Only this is a K8s resource

configMapGenerator:
  - name: pdvd-values
    files:
      - values.yaml         # Helm values go into a ConfigMap

secretGenerator:
  - name: pdvd-secrets
    files:
      - secrets.enc.yaml    # SOPS encrypted, generates Secret

generatorOptions:
  disableNameSuffixHash: true
